### ISSUE TITLE
Adding graph to app

### ISSUE THREAD

**Issue by spaztacular** [freshking/DynamicGraphView#7]
I followed your exact instructions to copy graphView.h amd .m to app, then I put exactly what you put in the viewcontroller .h and .m, am I supposed to do something else? Sorry if its a really stupid question.

**Comment by freshking** [comment]
Please explain exactly the problem you are having. Then I can help a lot better.

**Comment by spaztacular** [comment]
Just realized I am using xcode 5, which offers no method to use XIB's. Do you have a Storyboard version of this?

**Comment by spaztacular** [comment]
Sorry, I was able to do it quite easily, i just had made a really stupid mistake. I still do have one question however. Is their a way to make the graph be on a uiview? or like a scroll view?
